import { TelemetryParameterMeta } from '../models/telemetry.model';

/**
 * Canonical parameter metadata for all telemetry channels displayed
 * in the GCS dashboard. Defines display labels, units, decimal precision,
 * category groupings, and threshold boundaries for status evaluation.
 */
export const PARAMETER_METADATA: TelemetryParameterMeta[] = [
  {
    key: 'engine_rpm',
    label: 'Engine RPM',
    unit: 'RPM',
    decimals: 0,
    category: 'powertrain',
    nominalMin: 1800,
    nominalMax: 3200,
    cautionMax: 3500,
    criticalMax: 3800,
  },
  {
    key: 'cht',
    label: 'Cylinder Head Temp',
    unit: '°C',
    decimals: 1,
    category: 'thermal',
    nominalMin: 90,
    nominalMax: 195,
    cautionMax: 215,
    criticalMax: 235,
  },
  {
    key: 'egt',
    label: 'Exhaust Gas Temp',
    unit: '°C',
    decimals: 0,
    category: 'thermal',
    nominalMin: 600,
    nominalMax: 880,
    cautionMax: 930,
    criticalMax: 990,
  },
  {
    key: 'oil_pressure',
    label: 'Oil Pressure',
    unit: 'PSI',
    decimals: 1,
    category: 'lubrication',
    cautionMin: 35,
    criticalMin: 22,
    nominalMin: 40,
    nominalMax: 65,
    cautionMax: 75,
  },
  {
    key: 'oil_temperature',
    label: 'Oil Temp',
    unit: '°C',
    decimals: 1,
    category: 'lubrication',
    nominalMin: 70,
    nominalMax: 100,
    cautionMax: 110,
    criticalMax: 125,
  },
  {
    key: 'fuel_mass_flow_gps',
    label: 'Fuel Mass Flow',
    unit: 'g/s',
    decimals: 2,
    category: 'combustion',
    nominalMin: 2.0,
    nominalMax: 18.0,
  },
  {
    key: 'vibration_g_rms',
    label: 'Vibration',
    unit: 'g RMS',
    decimals: 2,
    category: 'powertrain',
    nominalMin: 0.1,
    nominalMax: 0.6,
    cautionMax: 0.85,
    criticalMax: 1.25,
  },
  {
    key: 'throttle',
    label: 'Throttle Position',
    unit: '%',
    decimals: 1,
    category: 'powertrain',
    nominalMin: 0,
    nominalMax: 100,
  },
  {
    key: 'engine_load',
    label: 'Engine Load',
    unit: '%',
    decimals: 1,
    category: 'powertrain',
    nominalMin: 10,
    nominalMax: 85,
  },
  {
    key: 'afr',
    label: 'Air-Fuel Ratio',
    unit: 'AFR',
    decimals: 1,
    category: 'combustion',
    cautionMin: 12.0,
    criticalMin: 10.5,
    nominalMin: 13.5,
    nominalMax: 15.5,
    cautionMax: 16.5,
    criticalMax: 18.0,
  },
  {
    key: 'brake_power_w',
    label: 'Brake Power',
    unit: 'kW',
    decimals: 1,
    category: 'powertrain',
    nominalMin: 10,
    nominalMax: 120,
  },
  {
    key: 'engine_torque_nm',
    label: 'Engine Torque',
    unit: 'N·m',
    decimals: 1,
    category: 'powertrain',
    nominalMin: 50,
    nominalMax: 260,
  },
  {
    key: 'battery_voltage',
    label: 'Battery Voltage',
    unit: 'V',
    decimals: 1,
    category: 'electrical',
    cautionMin: 22.5,
    criticalMin: 20.0,
    nominalMin: 23.5,
    nominalMax: 26.0,
  },
  {
    key: 'alternator_voltage',
    label: 'Alternator Voltage',
    unit: 'V',
    decimals: 1,
    category: 'electrical',
    cautionMin: 26.5,
    criticalMin: 24.0,
    nominalMin: 27.5,
    nominalMax: 29.0,
  },
  {
    key: 'injection_timing',
    label: 'Injection Timing',
    unit: '°BTDC',
    decimals: 1,
    category: 'combustion',
    nominalMin: 19,
    nominalMax: 25,
    cautionMin: 16,
    cautionMax: 28,
    criticalMin: 13,
    criticalMax: 31,
  },
];
