"""
feature_adapter.py
-------------------
Single source of truth for turning one simulator tick into the feature
vector the trained models (in the top-level ``models/`` directory) expect.

Why this exists: the RUL regressors, the fault classifier, the anomaly
detector, and the sensor-drift predictors were ALL trained on the same 12
raw sensor columns + their rolling mean/std (5-tick window) -- see
``src/preprocess.py`` in the main project. Computing that feature row in
one place, once per tick, and handing the same row to all four model
families keeps them consistent and avoids four slightly-different
hand-rolled adapters drifting apart over time.

This replaces an earlier version of ``rul_predictor.py`` that approximated
manifold pressure as ``24.0 + engine_load * 0.08`` with a comment noting
"the simulator has no manifold channel." That was wrong -- the physics
engine (``physics_engine.py``) genuinely computes manifold pressure from
first principles (``physics/airflow.py::manifold_pressure``), it just
wasn't threaded through to the telemetry/ML layer. This module uses the
real value instead.
"""

from __future__ import annotations

from collections import deque
from typing import Any, Dict, Optional

import numpy as np
import pandas as pd

# The 12 raw sensor/context columns every model in models/ was trained on,
# in the exact order preprocess.py used (order doesn't matter for dict-based
# lookups, but keeping it explicit avoids silent column-order bugs).
RAW_COLUMNS = [
    "cylinder_head_temp_C",
    "exhaust_gas_temp_C",
    "oil_temp_C",
    "oil_pressure_psi",
    "vibration_g_rms",
    "fuel_flow_L_per_hr",
    "manifold_pressure_inHg",
    "rpm",
    "battery_voltage_V",
    "injection_timing_deg",
    "altitude_ft",
    "ambient_temp_C",
]

ROLLING_WINDOW = 5  # matches src/preprocess.py's rolling feature window

PA_PER_INHG = 3386.389  # exact conversion, 1 inHg = 3386.389 Pa
GPS_TO_L_PER_HR = 3600.0 / 740.0  # avgas density ~740 g/L


# --------------------------------------------------------------------------
# Domain-gap calibration
# --------------------------------------------------------------------------
# The physics simulator (Simulated_engine/) and the ML training data
# (data/piston_engine_data.csv, generated by src/generate_data.py) were
# built as two genuinely separate subsystems and were never calibrated
# against each other. Comparing a live physics-simulator nominal_cruise
# run against the Normal-labeled rows of the real training data shows they
# disagree substantially on several channels' native scale -- e.g. the
# physics engine's nominal CHT runs ~83°C vs ~183°C in training data, and
# its fuel mass flow corresponds to ~2.6 L/hr vs ~19 L/hr in training data.
# Feeding physics-native numbers straight into models trained on the other
# distribution produces systematically wrong classifications (verified:
# it produced a constant, spurious "Electrical Fault" + "Sensor Drift"
# diagnosis while completely missing an actual injected cooling fault).
#
# The fix here is standard distribution/domain alignment (a z-score
# rescale measured from real data on both sides), not an arbitrary fudge
# factor: aligned = train_mean + (physics_value - phys_mean) * (train_std / phys_std).
# This preserves genuine deviations (a real fault progressing in physics
# space still shows up as a deviation in aligned space) while correcting
# the baseline/scale mismatch between the two subsystems.
#
# Stats below were computed directly from a LIVE nominal_cruise simulator
# run (not the static Simulated_engine/output/*.csv export, which lacks
# the raw physics dict manifold pressure needs and predates the current
# ws_server.py battery-voltage stub) vs. the Normal-labeled rows of
# data/piston_engine_data.csv; see src/calibrate_physics_adapter.py for the
# exact, reproducible computation.
#
# KNOWN LIMITATION: the physics engine's EGT model saturates near its own
# 1400K (1126.85°C) ceiling even during ordinary nominal cruise in this
# build (physics std is only ~2.6°C), so aligned EGT has very little real
# dynamic range to work with regardless of this rescale -- it is included
# for completeness but is a weak signal until the physics thermal model
# itself is recalibrated. This is disclosed rather than hidden.
#
# calibration tuples below are (phys_mean, phys_std, train_mean, train_std)
CALIBRATION: Dict[str, tuple] = {
    "cylinder_head_temp_C": (83.01, 2.02, 182.68, 5.25),
    "exhaust_gas_temp_C": (1126.81, 2.57, 779.49, 14.82),
    "oil_temp_C": (79.98, 1.07, 95.94, 3.48),
    "oil_pressure_psi": (60.77, 5.56, 68.22, 3.49),
    "fuel_flow_L_per_hr": (2.62, 0.63, 19.10, 0.87),
    "altitude_ft": (9999.78, 12.47, 13326.94, 2544.44),
    "ambient_temp_C": (15.03, 0.30, -3.71, 10.64),
    # Measured from a live simulator run (not the static CSV export, which
    # lacks the raw physics dict manifold pressure needs, and doesn't
    # reflect the ws_server.py battery-voltage stub) -- see
    # src/calibrate_physics_adapter.py for how these were derived.
    "manifold_pressure_inHg": (9.33, 0.86, 26.69, 0.71),
    "battery_voltage_V": (24.00, 0.05, 27.75, 0.29),
    "injection_timing_deg": (19.60, 0.27, 21.65, 0.45),
    # vibration_g_rms and rpm were measured close enough between the two
    # systems (rpm has real, meaningful transient variance from actual
    # engine dynamics that should NOT be smoothed away) that rescaling
    # them would add noise rather than remove bias, so they pass through
    # unchanged.
}


def _align(column: str, value: float) -> float:
    cal = CALIBRATION.get(column)
    if not cal:
        return value
    phys_mean, phys_std, train_mean, train_std = cal
    if phys_std <= 1e-6:
        return value
    return train_mean + (value - phys_mean) * (train_std / phys_std)


def _to_float(value: Any, default: float = 0.0) -> float:
    try:
        number = float(value)
        return number if np.isfinite(number) else default
    except (TypeError, ValueError):
        return default


def adapt_raw_features(variables: Dict[str, Any], phys: Optional[Dict[str, Any]] = None) -> Dict[str, float]:
    """Translate one simulator tick (its telemetry `variables` dict, plus the
    richer internal `phys` dict from PhysicsEngine.calculate_instantaneous_physics,
    if available) into the 12 raw training columns, using REAL physics values
    wherever the simulator computes them -- not a fudge-factor proxy -- then
    applies the measured CALIBRATION alignment above.
    """
    phys = phys or {}
    fuel_mass_flow_gps = _to_float(variables.get("fuel_mass_flow_gps"))

    # Manifold pressure: real physics value (Pa) when available, converted to
    # inHg. Only falls back to a documented proxy if phys wasn't supplied
    # (e.g. a caller replaying exported CSVs that didn't log the raw Pa value).
    if "manifold_pressure_pa" in phys:
        manifold_inhg = _to_float(phys["manifold_pressure_pa"]) / PA_PER_INHG
    else:
        engine_load = _to_float(variables.get("engine_load"), 45.0)
        manifold_inhg = 24.0 + engine_load * 0.08  # documented fallback proxy only

    raw = {
        "cylinder_head_temp_C": _to_float(variables.get("cht")),
        "exhaust_gas_temp_C": _to_float(variables.get("egt")),
        "oil_temp_C": _to_float(variables.get("oil_temperature")),
        "oil_pressure_psi": _to_float(variables.get("oil_pressure")),
        "vibration_g_rms": _to_float(variables.get("vibration_g_rms")),
        "fuel_flow_L_per_hr": fuel_mass_flow_gps * GPS_TO_L_PER_HR,
        "manifold_pressure_inHg": manifold_inhg,
        "rpm": _to_float(variables.get("engine_rpm")),
        "battery_voltage_V": _to_float(variables.get("battery_voltage"), 27.5),
        "injection_timing_deg": _to_float(variables.get("injection_timing"), 22.0),
        "altitude_ft": _to_float(variables.get("altitude")),
        "ambient_temp_C": _to_float(variables.get("temperature")),
    }
    return {col: _align(col, val) for col, val in raw.items()}


class TelemetryFeaturePipeline:
    """Keeps the rolling window of recent raw readings for ONE engine/session
    and produces the full (raw + rolling mean/std) feature row on each tick.
    """

    def __init__(self, window: int = ROLLING_WINDOW):
        self.window = window
        self._history: deque[Dict[str, float]] = deque(maxlen=window)

    def reset(self) -> None:
        self._history.clear()

    def push(self, variables: Dict[str, Any], phys: Optional[Dict[str, Any]] = None) -> Dict[str, float]:
        raw = adapt_raw_features(variables, phys)
        self._history.append(raw)

        row: Dict[str, float] = dict(raw)
        hist_df = pd.DataFrame(self._history)
        for col in RAW_COLUMNS:
            row[f"{col}_roll_mean"] = float(hist_df[col].mean())
            row[f"{col}_roll_std"] = float(hist_df[col].std(ddof=1)) if len(hist_df) > 1 else 0.0
        return row

    def row_as_frame(self, row: Dict[str, float], feature_cols: list) -> pd.DataFrame:
        return pd.DataFrame([[row.get(c, 0.0) for c in feature_cols]], columns=feature_cols)
